spring.application.name                      = sharding_demo
logging.level.org.springframework.aop        = DEBUG
# Hikari Pool Configuration
spring.datasource.hikari.minimum-idle        = 5
spring.datasource.hikari.maximum-pool-size   = 10
spring.datasource.hikari.connection-timeout  = 30000
spring.datasource.hikari.idle-timeout        = 600000

spring.datasource.driver-class-name    = org.postgresql.Driver

# Data Source: datasource1
spring.shard1.datasource.url      = jdbc:postgresql://localhost:5432/webshop_shard1
spring.shard1.datasource.username = postgres
spring.shard1.datasource.password = postgres

# Data Source: datasource2
spring.shard2.datasource.url      = jdbc:postgresql://localhost:5432/webshop_shard2
spring.shard2.datasource.username = postgres
spring.shard2.datasource.password = postgres


jwt.secret                                   = abcdefgabcdefgabcdefgabcdefgabcdefgabcdefg
